name = "test"
pages_build_output_dir = "dist"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]


# Cloudflare account (sulimierski.jakub@gmail.com)
# account_id = "c08a11ec88e62b32f91afc2c83b4c687"

[[d1_databases]]
binding = "DB"
database_name = "test-d1"
database_id = "a2fcb0f5-33a5-471a-98eb-d2517c11aa86"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "test-bucket"
